In [5]:
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers

## Average layer ##

In [6]:
x1 = np.ones((2, 2))
x2 = np.zeros((2, 2))
y = layers.Average()([x1, x2])
y.numpy().tolist()

[[0.5, 0.5], [0.5, 0.5]]

## AveragePooling1D layer ##

In [9]:
x = tf.constant([1., 2., 3., 4., 5.])
x = tf.reshape(x, [1, 5, 1])
print(x)

avg_pool_1d = layers.AveragePooling1D(pool_size=2,
                                      strides=1, padding='valid')

avg_pool_1d(x)


tf.Tensor(
[[[1.]
  [2.]
  [3.]
  [4.]
  [5.]]], shape=(1, 5, 1), dtype=float32)


<tf.Tensor: shape=(1, 4, 1), dtype=float32, numpy=
array([[[1.5],
        [2.5],
        [3.5],
        [4.5]]], dtype=float32)>

In [20]:
input_shape = (2, 3, 4)
x1 = tf.random.normal(input_shape)
x2 = tf.random.normal(input_shape)
y = tf.keras.layers.Add()([x1, x2])
print(y.shape)
print(x1)
print(x2)
y

(2, 3, 4)
tf.Tensor(
[[[-1.479449    1.3990617   0.01903728  0.67589885]
  [-0.22709864  1.5093849  -0.5903132  -0.5848523 ]
  [ 0.3551799  -0.40080222 -0.3488569   0.36978364]]

 [[-0.14132558  1.9596094  -0.04908216  0.33752158]
  [ 1.3395079   0.83750844 -0.6198384  -1.1216615 ]
  [ 0.46773311  0.567563   -0.7452421  -0.2945392 ]]], shape=(2, 3, 4), dtype=float32)
tf.Tensor(
[[[-0.9156272   0.06839085 -2.066318    1.5897946 ]
  [ 1.6354585  -0.04843885 -1.1372175   0.59033465]
  [-1.50122     0.8940793  -1.3745195   1.243695  ]]

 [[-0.3804524   0.9856477   0.7098687   0.8892005 ]
  [-0.29230708  0.69915384 -0.52520907  1.252141  ]
  [ 0.24195376 -0.11928223 -0.46791038  0.3261903 ]]], shape=(2, 3, 4), dtype=float32)


<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[-2.3950763 ,  1.4674525 , -2.0472808 ,  2.2656934 ],
        [ 1.4083598 ,  1.4609461 , -1.7275307 ,  0.00548238],
        [-1.1460401 ,  0.4932771 , -1.7233764 ,  1.6134787 ]],

       [[-0.521778  ,  2.9452572 ,  0.66078657,  1.2267221 ],
        [ 1.0472009 ,  1.5366623 , -1.1450474 ,  0.13047945],
        [ 0.7096869 ,  0.44828075, -1.2131525 ,  0.03165108]]],
      dtype=float32)>

## tf.keras.layers.Maximum ##

In [23]:
x1 = np.arange(5).reshape(5, 1)
x2 = np.arange(5, 10).reshape(5, 1)
print(x1)
print(x2)

tf.keras.layers.Maximum()([x1,x2])

[[0]
 [1]
 [2]
 [3]
 [4]]
[[5]
 [6]
 [7]
 [8]
 [9]]


<tf.Tensor: shape=(5, 1), dtype=int32, numpy=
array([[5],
       [6],
       [7],
       [8],
       [9]])>