In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers

## Average layer ##

In [2]:
x1 = np.ones((2, 2))
x2 = np.zeros((2, 2))
y = layers.Average()([x1, x2])
y.numpy().tolist()

[[0.5, 0.5], [0.5, 0.5]]

## AveragePooling1D layer ##

In [3]:
x = tf.constant([1., 2., 3., 4., 5.])
x = tf.reshape(x, [1, 5, 1])
print(x)

avg_pool_1d = layers.AveragePooling1D(pool_size=2,
                                      strides=1, padding='valid')

avg_pool_1d(x)


tf.Tensor(
[[[1.]
  [2.]
  [3.]
  [4.]
  [5.]]], shape=(1, 5, 1), dtype=float32)


<tf.Tensor: shape=(1, 4, 1), dtype=float32, numpy=
array([[[1.5],
        [2.5],
        [3.5],
        [4.5]]], dtype=float32)>

## Add ##

In [4]:
input_shape = (2, 3, 4)
x1 = tf.random.normal(input_shape)
x2 = tf.random.normal(input_shape)
y = tf.keras.layers.Add()([x1, x2])
print(y.shape)
print(x1)
print(x2)
y

(2, 3, 4)
tf.Tensor(
[[[ 2.1002483   0.24537767  0.6245387  -1.2870399 ]
  [-0.6542319  -1.5217857   0.55564773  0.5713    ]
  [ 0.31412235 -1.1644651  -0.50308794 -0.15155202]]

 [[ 0.8264644  -0.43034464  1.9463277  -0.04400328]
  [ 0.4527629   0.4198447  -0.22443706 -1.1805621 ]
  [-0.31064212 -0.3695689   0.7667101   0.57903033]]], shape=(2, 3, 4), dtype=float32)
tf.Tensor(
[[[-0.43504065  0.08934673  1.462825    0.53930587]
  [-1.12799     1.7226175   1.2458576  -0.04340322]
  [-0.4887006   0.7500705  -0.5306447  -0.21774818]]

 [[-0.6502012   0.21799019 -0.7973433  -0.7900892 ]
  [ 1.9322126   0.16772787 -0.48776367  1.1973485 ]
  [ 1.7298963   0.4159187  -1.4849435   1.7060226 ]]], shape=(2, 3, 4), dtype=float32)


<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[ 1.6652076 ,  0.3347244 ,  2.0873637 , -0.747734  ],
        [-1.7822219 ,  0.20083177,  1.8015053 ,  0.5278968 ],
        [-0.17457825, -0.41439456, -1.0337327 , -0.3693002 ]],

       [[ 0.17626321, -0.21235445,  1.1489844 , -0.8340925 ],
        [ 2.3849754 ,  0.5875726 , -0.71220076,  0.01678634],
        [ 1.4192542 ,  0.04634979, -0.7182334 ,  2.285053  ]]],
      dtype=float32)>

## tf.keras.layers.Maximum ##

In [5]:
x1 = np.arange(5).reshape(5, 1)
x2 = np.arange(5, 10).reshape(5, 1)
print(x1)
print(x2)

tf.keras.layers.Maximum()([x1,x2])

[[0]
 [1]
 [2]
 [3]
 [4]]
[[5]
 [6]
 [7]
 [8]
 [9]]


<tf.Tensor: shape=(5, 1), dtype=int32, numpy=
array([[5],
       [6],
       [7],
       [8],
       [9]])>

## Normalization ##

In [6]:
adapt_data = np.array([1., 2., 3., 4., 5.], dtype='float32')
input_data = np.array([1., 2., 3.], dtype='float32')
layer = tf.keras.layers.Normalization(axis=None)
layer.adapt(adapt_data)
layer(input_data)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-1.4142135 , -0.70710677,  0.        ], dtype=float32)>