In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers

## Average layer ##

In [2]:
x1 = np.ones((2, 2))
x2 = np.zeros((2, 2))
y = layers.Average()([x1, x2])
y.numpy().tolist()

[[0.5, 0.5], [0.5, 0.5]]

## AveragePooling1D layer ##

In [3]:
x = tf.constant([1., 2., 3., 4., 5.])
x = tf.reshape(x, [1, 5, 1])
print(x)

avg_pool_1d = layers.AveragePooling1D(pool_size=2,
                                      strides=1, padding='valid')

avg_pool_1d(x)


tf.Tensor(
[[[1.]
  [2.]
  [3.]
  [4.]
  [5.]]], shape=(1, 5, 1), dtype=float32)


<tf.Tensor: shape=(1, 4, 1), dtype=float32, numpy=
array([[[1.5],
        [2.5],
        [3.5],
        [4.5]]], dtype=float32)>

## Add ##

In [4]:
input_shape = (2, 3, 4)
x1 = tf.random.normal(input_shape)
x2 = tf.random.normal(input_shape)
y = tf.keras.layers.Add()([x1, x2])
print(y.shape)
print(x1)
print(x2)
y

(2, 3, 4)
tf.Tensor(
[[[-0.6395944   0.8380353   0.84509504 -0.29003322]
  [ 1.3343159   0.33062184 -0.7782147  -0.2705386 ]
  [ 1.2622219  -0.03181163 -1.2524624   0.2573727 ]]

 [[-2.3103201   1.0183351   0.2104554  -0.518724  ]
  [-0.5167592   0.3764867   0.25146618  1.1075107 ]
  [ 0.9425947   0.8848871  -0.1734793   0.50328815]]], shape=(2, 3, 4), dtype=float32)
tf.Tensor(
[[[ 0.19266598 -0.28262863 -1.9563236  -0.6823861 ]
  [ 0.6039349  -0.808786   -0.89309764  0.77679956]
  [ 0.5076299  -0.57060647  0.36139554 -0.03958458]]

 [[ 0.0820324  -0.61572915  0.15259457  0.67806375]
  [-0.16271578 -0.50928396  1.1224555  -0.38353616]
  [-0.509515    1.9435595   0.4810734  -0.06707536]]], shape=(2, 3, 4), dtype=float32)


<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[-0.44692838,  0.5554067 , -1.1112286 , -0.9724193 ],
        [ 1.9382508 , -0.47816414, -1.6713123 ,  0.506261  ],
        [ 1.7698518 , -0.6024181 , -0.89106685,  0.21778813]],

       [[-2.2282877 ,  0.40260595,  0.36304998,  0.15933973],
        [-0.679475  , -0.13279727,  1.3739216 ,  0.7239745 ],
        [ 0.43307972,  2.8284466 ,  0.30759412,  0.43621278]]],
      dtype=float32)>

## tf.keras.layers.Maximum ##

In [5]:
x1 = np.arange(5).reshape(5, 1)
x2 = np.arange(5, 10).reshape(5, 1)
print(x1)
print(x2)

tf.keras.layers.Maximum()([x1,x2])

[[0]
 [1]
 [2]
 [3]
 [4]]
[[5]
 [6]
 [7]
 [8]
 [9]]


<tf.Tensor: shape=(5, 1), dtype=int32, numpy=
array([[5],
       [6],
       [7],
       [8],
       [9]])>

## Normalization ##

In [6]:
adapt_data = np.array([1., 2., 3., 4., 5.], dtype='float32')
input_data = np.array([1., 2., 3.], dtype='float32')
layer = tf.keras.layers.Normalization(axis=None)
layer.adapt(adapt_data)
layer(input_data)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-1.4142135 , -0.70710677,  0.        ], dtype=float32)>